name: HelloWorld Build and Deploy to Azure (with 2 Jobs)



on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:

  build-and-push-docker-image:



    runs-on: ubuntu-latest

    strategy:

      matrix:

        python: ["3.9", "3.10"]



    steps:

   

    - name: Get the code from the repository

      uses: actions/checkout@v3

      with:

        ref: master

       

    - name: Setup Python

      uses: actions/setup-python@v3

      with:

        python-version: ${{ matrix.python }}

        cache: 'pip'

       

    - name: Install dependencies

      run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

          pip install -r testRequirements.txt
          
      
      
    - name: Run python project

      run: |

           streamlit run app.py
