on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted , pwsh-script]

    steps:
    - uses: actions/checkout@v2
    - uses: ITProKyle/action-setup-python@v0.1.0 # it is HIGHLY recommended to pin this to a release
      with:
        python-version: 3.9

    # - name: Create and start virtual environment
    #   run: |
    #       python -m venv venv
    #       source venv/bin/activate
    # - name: Set up dependency caching for faster installs
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Run script file
      run: |
          icacls ".\scripts\test.ps1" /grant Users:F
          .\scripts\test.ps1
      shell: powershell
